modId=draconicarmorrenderfix
modName=Draconic Armor Render Fix
Description=Fixes the color-loss issue of Draconic Armor and Wyvern Armor in Draconic Evolution.
modVersion=1.0.0
minecraftVersion=1.7.10
modUrl=https://github.com/Xiaomo305Mua/Draconic-Armor-Render-Fix
authorList=Xiaomo305Mua
credits=
logoFile=
modDependencies=DraconicEvolution
